# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class TInterface(object):
    def setupUi(self, Application):
        Application.setObjectName("Application")
        Application.resize(840, 352)
        font = QtGui.QFont()
        font.setPointSize(14)
        Application.setFont(font)
        self.bracket1 = QtWidgets.QLabel(Application)
        self.bracket1.setGeometry(QtCore.QRect(20, 0, 20, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.bracket1.setFont(font)
        self.bracket1.setTextFormat(QtCore.Qt.PlainText)
        self.bracket1.setScaledContents(False)
        self.bracket1.setObjectName("bracket1")
        self.ar = QtWidgets.QTextEdit(Application)  # вещественная часть коэффициента a
        self.ar.setGeometry(QtCore.QRect(30, 10, 61, 41))
        self.ar.setObjectName("ar")
        self.plus1 = QtWidgets.QLabel(Application)
        self.plus1.setGeometry(QtCore.QRect(100, 10, 21, 31))
        self.plus1.setObjectName("plus1")
        self.ai = QtWidgets.QTextEdit(Application)  # мнимая часть коэффициента a
        self.ai.setGeometry(QtCore.QRect(120, 10, 61, 41))
        self.ai.setObjectName("ai")
        self.a_coefficient = QtWidgets.QLabel(Application)
        self.a_coefficient.setGeometry(QtCore.QRect(190, 10, 81, 31))
        self.a_coefficient.setObjectName("a_coefficient")
        self.br = QtWidgets.QTextEdit(Application)  # вещественная часть коэффициента b
        self.br.setGeometry(QtCore.QRect(270, 10, 61, 41))
        self.br.setObjectName("br")
        self.plus2 = QtWidgets.QLabel(Application)
        self.plus2.setGeometry(QtCore.QRect(340, 10, 21, 31))
        self.plus2.setObjectName("plus2")
        self.bi = QtWidgets.QTextEdit(Application)  # мнимая часть коэффициента b
        self.bi.setGeometry(QtCore.QRect(360, 10, 61, 41))
        self.bi.setObjectName("bi")
        self.b_coefficient = QtWidgets.QLabel(Application)
        self.b_coefficient.setGeometry(QtCore.QRect(430, 10, 71, 31))
        self.b_coefficient.setObjectName("b_coefficient")
        self.cr = QtWidgets.QTextEdit(Application)
        self.cr.setGeometry(QtCore.QRect(500, 10, 61, 41))
        self.cr.setObjectName("cr")  # вещественная часть коэффициента c
        self.ci = QtWidgets.QTextEdit(Application)
        self.ci.setGeometry(QtCore.QRect(590, 10, 61, 41))
        self.ci.setObjectName("ci")  # мнимая часть коэффициента c
        self.c_coefficient = QtWidgets.QLabel(Application)
        self.c_coefficient.setGeometry(QtCore.QRect(660, 10, 51, 31))
        self.c_coefficient.setObjectName("c_coefficient")
        self.x_label = QtWidgets.QLabel(Application)
        self.x_label.setGeometry(QtCore.QRect(20, 70, 55, 51))
        self.x_label.setObjectName("x_label")
        self.xr = QtWidgets.QTextEdit(Application)
        self.xr.setGeometry(QtCore.QRect(70, 80, 61, 41))
        self.xr.setObjectName("xr")  # вещественная часть параметра x
        self.xi = QtWidgets.QTextEdit(Application)
        self.xi.setGeometry(QtCore.QRect(160, 80, 61, 41))
        self.xi.setObjectName("xi")  # мнимая часть парамметра x
        self.bracket2 = QtWidgets.QLabel(Application)
        self.bracket2.setGeometry(QtCore.QRect(230, 80, 21, 31))
        self.bracket2.setObjectName("bracket2")
        self.solve_btn = QtWidgets.QPushButton(Application)
        self.solve_btn.setGeometry(QtCore.QRect(320, 230, 201, 51))
        self.solve_btn.setObjectName("solve_btn")  # кнопка решения уравнения
        self.calculate_btn = QtWidgets.QPushButton(Application)
        self.calculate_btn.setGeometry(QtCore.QRect(320, 290, 201, 51))
        self.calculate_btn.setObjectName("calculate_btn")  # кнопка вычисления значения многочлена
        self.x1_label = QtWidgets.QLabel(Application)
        self.x1_label.setGeometry(QtCore.QRect(20, 130, 55, 51))
        self.x1_label.setObjectName("x1_label")
        self.x2_label = QtWidgets.QLabel(Application)
        self.x2_label.setGeometry(QtCore.QRect(20, 190, 55, 31))
        self.x2_label.setObjectName("x2_label")
        self.value = QtWidgets.QLabel(Application)  # поле вывода значения многочлена
        self.value.setGeometry(QtCore.QRect(710, 0, 121, 51))
        self.value.setText("")
        self.value.setObjectName("value")
        self.plus3 = QtWidgets.QLabel(Application)
        self.plus3.setGeometry(QtCore.QRect(570, 10, 21, 31))
        self.plus3.setObjectName("plus3")
        self.plus4 = QtWidgets.QLabel(Application)
        self.plus4.setGeometry(QtCore.QRect(140, 80, 21, 31))
        self.plus4.setObjectName("plus4")
        self.x1 = QtWidgets.QLabel(Application)  # поле вывода первого корня
        self.x1.setGeometry(QtCore.QRect(80, 130, 121, 51))
        self.x1.setText("")
        self.x1.setObjectName("x1")
        self.x2 = QtWidgets.QLabel(Application)  # поле вывода второго корня
        self.x2.setGeometry(QtCore.QRect(80, 180, 121, 51))
        self.x2.setText("")
        self.x2.setObjectName("x2")
        self.bracket1.raise_()
        self.ar.raise_()
        self.plus1.raise_()
        self.ai.raise_()
        self.a_coefficient.raise_()
        self.br.raise_()
        self.plus2.raise_()
        self.bi.raise_()
        self.b_coefficient.raise_()
        self.cr.raise_()
        self.ci.raise_()
        self.c_coefficient.raise_()
        self.x_label.raise_()
        self.xr.raise_()
        self.xi.raise_()
        self.bracket2.raise_()
        self.solve_btn.raise_()
        self.calculate_btn.raise_()
        self.x1_label.raise_()
        self.x2_label.raise_()
        self.plus3.raise_()
        self.value.raise_()
        self.plus4.raise_()
        self.x1.raise_()
        self.x2.raise_()

        self.retranslateUi(Application)
        QtCore.QMetaObject.connectSlotsByName(Application)

    def retranslateUi(self, Application):
        _translate = QtCore.QCoreApplication.translate
        Application.setWindowTitle(_translate("Application", "Polinom application"))
        self.bracket1.setText(_translate("Application", "("))
        self.plus1.setText(_translate("Application", "+"))
        self.a_coefficient.setText(_translate("Application", "i)x² + ("))
        self.plus2.setText(_translate("Application", "+"))
        self.b_coefficient.setText(_translate("Application", "i)x + ("))
        self.c_coefficient.setText(_translate("Application", "i) ="))
        self.x_label.setText(_translate("Application", "x = ("))
        self.bracket2.setText(_translate("Application", "i)"))
        self.solve_btn.setText(_translate("Application", "solve equation"))
        self.calculate_btn.setText(_translate("Application", "calculate polinom"))
        self.x1_label.setText(_translate("Application", "x1 ="))
        self.x2_label.setText(_translate("Application", "x2 ="))
        self.plus3.setText(_translate("Application", "+"))
        self.plus4.setText(_translate("Application", "+"))

    # названия полей и кнопок:

    # ar, ai - вещественная и мнимая часть a;
    # br, bi - вещественная и мнимая часть b;
    # cr, ci - вещественная и мнимая часть c;
    # xr, xi - вещественная и мнимая часть x;
    # solve_btn - кнопка решения уравнения;
    # calculate_btn - кнопка вычисления значения многочлена;
    # value - поле вывода значения многочлена;
    # x1, x2 - поля вывода корней.
